### ISSUE TITLE
Can't download some files

### ISSUE THREAD

**Issue by IgorShadurin** [xssnick/tonutils-storage#16]
I'm trying to download some files, but they won't download. For 2 files, it displays up-to-date information about them, but does not download. For the third file does not even display information. All files are distributed from 1 server. Some other files from this server could be downloaded

<img width="1171" alt="Screenshot 2023-08-15 at 12 38 03" src="https://github.com/xssnick/tonutils-storage/assets/1595061/34fc55c6-0693-4fe9-8c61-164dcf4c6803">

40c17ab52853a24190e6b627100d4394fd51595705527261a0bf4d642a0a7f4c
ef155134d49cd4515691226a7eeb31965a34ea245f1906901eac8e45d539ae9a
04c80c328c4b06197be09b5126b042a976ce7fab5a766031c0291882a2609fde

**Comment by xssnick** [comment]
Are those files hosted using tonutils-storage or using original storage-daemon?

**Comment by IgorShadurin** [comment]
Storage-daemon. 
also, after several hours of work, information about the file 04c80c328c4b06197be09b5126b042a976ce7fab5a766031c0291882a2609fde was received and it was downloaded. The rest didn't download.

**Comment by xssnick** [comment]
Original storage-daemon has such issue when it may not give information and files pieces for a long time. Try to use tonutils-storage on server side, it is stable and ready to use in projects imo :)

**Comment by xssnick** [comment]
Thre is also an [API](https://github.com/xssnick/tonutils-storage#http-api) so you can use it in your backend logic
