### ISSUE TITLE
Linux CLI do not support Copy/Paste

### ISSUE THREAD

**Issue by MicroNovaX** [xssnick/tonutils-storage#17]
<img width="952" alt="image" src="https://github.com/xssnick/tonutils-storage/assets/23459010/d5fb3da6-6001-41a7-8ffa-f01af951bbcb">

**Comment by xssnick** [comment]
Hi, it depends on terminal app you are running, for some of them Ctrl + Shift + V works, somewhere Insert button, and somewhere you need to right click and paste/copy.
